// <auto-generated />
using System;
using ContactInfoApp.Server.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactInfoApp.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220110222126_SearchContactHistoryComments")]
    partial class SearchContactHistoryComments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ContactInfoApp.Server.Persistence.Entities.SearchContactHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSpam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TagCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SearchContactHistory");
                });

            modelBuilder.Entity("ContactInfoApp.Server.Persistence.Entities.SearchContactHistoryComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Disliked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Liked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchContactHistoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SearchContactHistoryId");

                    b.ToTable("SearchContactHistoryComments");
                });

            modelBuilder.Entity("ContactInfoApp.Server.Persistence.Entities.SearchContactHistoryComment", b =>
                {
                    b.HasOne("ContactInfoApp.Server.Persistence.Entities.SearchContactHistory", "SearchContactHistory")
                        .WithMany("Comments")
                        .HasForeignKey("SearchContactHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchContactHistory");
                });

            modelBuilder.Entity("ContactInfoApp.Server.Persistence.Entities.SearchContactHistory", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
